// ============== Copyright (c) 2025 Monochrome Games ============== \\

#ifndef ZOMBIEPANIC_SHARED_WEAPON_H
#define ZOMBIEPANIC_SHARED_WEAPON_H

// bullet types
typedef enum
{
	BULLET_NONE = 0,
	BULLET_PLAYER_SIG, // sig
	BULLET_PLAYER_PPK, // ppk
	BULLET_PLAYER_CZ75, // cz75
	BULLET_PLAYER_GLOCK, // glock
	BULLET_PLAYER_MP5, // mp5
	BULLET_PLAYER_M16, // m16
	BULLET_PLAYER_SKS, // sks
	BULLET_PLAYER_357, // python
	BULLET_PLAYER_BUCKSHOT, // shotgun
	BULLET_PLAYER_DBARREL, // double barrel
	BULLET_PLAYER_CROWBAR, // crowbar swipe
	BULLET_PLAYER_SWIPE, // zombie swipe
	BULLET_PLAYER_SHARP, // sharp melee weapon

	BULLET_PLAYER_FAFO,

	BULLET_PROJECTILE, // used for nails etc.

	BULLET_MONSTER_9MM,
	BULLET_MONSTER_MP5,
	BULLET_MONSTER_12MM,
} Bullet;

// Sig
enum
{
	ANIM_SIG_IDLE1 = 0,
	ANIM_SIG_IDLE2,
	ANIM_SIG_IDLE3,
	ANIM_SIG_SHOOT1,
	ANIM_SIG_SHOOT2,
	ANIM_SIG_SHOOT3,
	ANIM_SIG_SHOOT_EMPTY,
	ANIM_SIG_RELOAD,
	ANIM_SIG_RELOAD_EMPTY,
	ANIM_SIG_UNLOAD,
	ANIM_SIG_DRAW,
	ANIM_SIG_HOLSTER,
	ANIM_SIG_DRAW_EMPTY,
	ANIM_SIG_HOLSTER_EMPTY,
	ANIM_SIG_IDLE1_EMPTY,
	ANIM_SIG_IDLE2_EMPTY,
	ANIM_SIG_IDLE3_EMPTY
};

// Shared Pistol animations
enum
{
	ANIM_PISTOL_IDLE1 = 0,
	ANIM_PISTOL_IDLE2,
	ANIM_PISTOL_IDLE3,
	ANIM_PISTOL_SHOOT,
	ANIM_PISTOL_SHOOT_EMPTY,
	ANIM_PISTOL_RELOAD,
	ANIM_PISTOL_RELOAD_EMPTY,
	ANIM_PISTOL_UNLOAD,
	ANIM_PISTOL_DRAW,
	ANIM_PISTOL_HOLSTER,
	ANIM_PISTOL_DRAW_EMPTY,
	ANIM_PISTOL_HOLSTER_EMPTY,
	ANIM_PISTOL_IDLE1_EMPTY,
	ANIM_PISTOL_IDLE2_EMPTY,
	ANIM_PISTOL_IDLE3_EMPTY
};

// Shotgun animations
enum
{
	ANIM_SHOTGUN_IDLE = 0,
	ANIM_SHOTGUN_IDLE2,
	ANIM_SHOTGUN_FIRE,
	ANIM_SHOTGUN_PUMP,
	ANIM_SHOTGUN_RELOAD_START,
	ANIM_SHOTGUN_RELOAD,
	ANIM_SHOTGUN_RELOAD_END,
	ANIM_SHOTGUN_DRAW,
	ANIM_SHOTGUN_HOLSTER,
	ANIM_SHOTGUN_UNLOAD,
};

// Double Barrel Shotgun animations
enum
{
	ANIM_DBARREL_IDLE1 = 0,
	ANIM_DBARREL_IDLE2,
	ANIM_DBARREL_FIRE1,
	ANIM_DBARREL_FIRE2,
	ANIM_DBARREL_FIRE3,
	ANIM_DBARREL_RELOAD,
	ANIM_DBARREL_RELOAD_SINGLE,
	ANIM_DBARREL_UNLOAD,
	ANIM_DBARREL_DRAW,
	ANIM_DBARREL_HOLSTER
};

// M16 / 5.56mm rifle animations
enum
{
	ANIM_AR556_LONGIDLE = 0,
	ANIM_AR556_IDLE1,
	ANIM_AR556_LAUNCH,
	ANIM_AR556_RELOAD,
	ANIM_AR556_DEPLOY,
	ANIM_AR556_FIRE1,
	ANIM_AR556_FIRE2,
	ANIM_AR556_FIRE3,
	ANIM_AR556_RELOAD_EMPTY,
	ANIM_AR556_UNLOAD,
	ANIM_AR556_HOLSTER
};

// SKS animations
enum
{
	ANIM_SKS_DRAW = 0,
	ANIM_SKS_IDLE_LONG,
	ANIM_SKS_IDLE_FIDGET,
	ANIM_SKS_IDLE,

	ANIM_SKS_SHOOT01,
	ANIM_SKS_SHOOT02,
	ANIM_SKS_SHOOT03,
	ANIM_SKS_SHOOT_EMPTY,

	ANIM_SKS_RELOAD_START,
	ANIM_SKS_RELOAD_LOOP,
	ANIM_SKS_RELOAD_END,

	ANIM_SKS_UNLOAD,
	ANIM_SKS_HOLSTER,

	ANIM_SKS_DRAW_EMPTY,
	ANIM_SKS_IDLE_LONG_EMPTY,
	ANIM_SKS_IDLE_FIDGET_EMPTY,
	ANIM_SKS_IDLE_EMPTY,

	ANIM_SKS_SHOOT_DRY,

	ANIM_SKS_RELOAD_EMPTY,
	ANIM_SKS_HOLSTER_EMPTY,

	ANIM_SKS_STAB_START,
	ANIM_SKS_STAB_HIT,
	ANIM_SKS_STAB_HITWORLD,
	ANIM_SKS_STAB_MISS,

	ANIM_SKS_STAB_START_EMPTY,
	ANIM_SKS_STAB_HIT_EMPTY,
	ANIM_SKS_STAB_HITWORLD_EMPTY,
	ANIM_SKS_STAB_MISS_EMPTY,
};

// MP5 / 9mm SMG animations
enum
{
	ANIM_MP5_LONGIDLE = 0,
	ANIM_MP5_IDLE1,
	ANIM_MP5_RELOAD,
	ANIM_MP5_DEPLOY,
	ANIM_MP5_FIRE1,
	ANIM_MP5_FIRE2,
	ANIM_MP5_FIRE3,
	ANIM_MP5_RELOAD_EMPTY,
	ANIM_MP5_UNLOAD,
	ANIM_MP5_HOLSTER
};

// .357 / Magnum revolver animations
enum
{
	ANIM_357_IDLE1 = 0,
	ANIM_357_FIDGET,
	ANIM_357_FIRE1,
	ANIM_357_RELOAD,
	ANIM_357_UNLOAD,
	ANIM_357_HOLSTER,
	ANIM_357_DRAW,
	ANIM_357_IDLE2,
	ANIM_357_IDLE3,
	// We unloaded the gun, no bullets.
	ANIM_357_UNLOADED_IDLE1,
	ANIM_357_UNLOADED_FIDGET,
	ANIM_357_UNLOADED_RELOAD,
	ANIM_357_UNLOADED_HOLSTER,
	ANIM_357_UNLOADED_DRAW,
	ANIM_357_UNLOADED_IDLE2,
	ANIM_357_UNLOADED_IDLE3,
};

// Melee animations
enum
{
	ANIM_MELEE_IDLE1 = 0,
	ANIM_MELEE_DRAW,
	ANIM_MELEE_HOLSTER,
	ANIM_MELEE_ATTACK1MISS,
	ANIM_MELEE_ATTACK1HIT,
	ANIM_MELEE_ATTACK2MISS,
	ANIM_MELEE_ATTACK2HIT,
	ANIM_MELEE_ATTACK3MISS,
	ANIM_MELEE_ATTACK3HIT,
	ANIM_MELEE_IDLE2,
	ANIM_MELEE_IDLE3,
	ANIM_MELEE_HEAVY_HOLD,
	ANIM_MELEE_HEAVY_HIT,
	ANIM_MELEE_HEAVY_MISS
};

// Grenades and other thrown explosives
enum
{
	ANIM_THROW_EXPLOSIVES_IDLE = 0,
	ANIM_THROW_EXPLOSIVES_FIDGET,
	ANIM_THROW_EXPLOSIVES_PINPULL,
	ANIM_THROW_EXPLOSIVES_THROW,
	ANIM_THROW_EXPLOSIVES_PINPULL2,
	ANIM_THROW_EXPLOSIVES_THROW2,
	ANIM_THROW_EXPLOSIVES_HOLSTER,
	ANIM_THROW_EXPLOSIVES_DRAW
};

// Satchel animations
enum
{
	ANIM_SATCHEL_IDLE = 0,
	ANIM_SATCHEL_FIDGET,
	ANIM_SATCHEL_DRAW,
	ANIM_SATCHEL_DROP,
	ANIM_SATCHEL_HOLSTER,
	ANIM_SATCHEL_DETONATOR_IDLE,
	ANIM_SATCHEL_DETONATOR_FIDGET,
	ANIM_SATCHEL_DETONATOR_DRAW,
	ANIM_SATCHEL_DETONATOR_DROP,
	ANIM_SATCHEL_DETONATOR_USE,
	ANIM_SATCHEL_DETONATOR_HOLSTER
};

// Barricade animations
enum
{
	// Used when not using the nailgun
	ANIM_BARRICADE_UNARMED1 = 0,
	ANIM_BARRICADE_UNARMED2,
	// Nailgun specific animations
	ANIM_BARRICADE_NAILGUN_DRAW,
	ANIM_BARRICADE_NAILGUN_HOLSTER,
	ANIM_BARRICADE_NAILGUN_IDLE1,
	ANIM_BARRICADE_NAILGUN_IDLE2,
	ANIM_BARRICADE_NAILGUN_IDLE3,
	ANIM_BARRICADE_NAILGUN_FIRE,
	ANIM_BARRICADE_NAILGUN_BARRICADE,
};

#endif